import sys
import time
import random
import os
import json

class C:
    OK = '\033[92m'
    WARN = '\033[93m'
    ERR = '\033[91m'
    INFO = '\033[94m'
    END = '\033[0m'

def clear_terminal():
    os.system('cls' if os.name == 'nt' else 'clear')

def typewriter(text, speed=0.03, realize_newlines=True):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed + random.uniform(0, 0.01))
    if realize_newlines:
        print()

def fast_load(text, delay=0.1):
    print(text)
    time.sleep(delay)

# Defining the 18-step AI proposal generated by the agent
ai_proposal = [
    {"device": "sidekick", "command": "to_well", "args": {"well": "H1"}},
    {"device": "minion", "command": "measure", "args": {}},
    {"device": "minion", "command": "motor_on", "args": {}},
    {"device": "sidekick", "command": "to_well", "args": {"well": "H1", "pump": "p1"}},
    {"device": "sidekick", "command": "dispense", "args": {"pump": "p1", "vol": 70.0}},
    {"device": "sidekick", "command": "to_well", "args": {"well": "H1", "pump": "p3"}},
    {"device": "sidekick", "command": "dispense", "args": {"pump": "p3", "vol": 140.0}},
    {"device": "sidekick", "command": "to_well", "args": {"well": "H1", "pump": "p4"}},
    {"device": "sidekick", "command": "dispense", "args": {"pump": "p4", "vol": 20.0}},
    {"device": "sidekick", "command": "park", "args": {}},
    {"device": "pybot-arm", "command": "move_to_xyz", "args": {"x": -47, "y": 122, "z": 60}},
    {"device": "pybot-arm", "command": "move_to_xyz", "args": {"x": -47, "y": 122, "z": 40}},
    {"device": "pybot-arm", "command": "read_sensor", "args": {}},
    {"device": "pybot-arm", "command": "move_to_xyz", "args": {"x": -47, "y": 122, "z": 60}},
    {"device": "pybot-arm", "command": "move_to_xyz", "args": {"x": -100, "y": 75, "z": 60}},
    {"device": "minion", "command": "motor_off", "args": {}},
    {"device": "sidekick", "command": "to_well", "args": {"well": "H1"}},
    {"device": "minion", "command": "measure", "args": {}}
]

def print_plan_review(plan):
    print(f"{C.WARN}--- PLAN REVIEW (CTRL-C to abort) ---{C.END}")
    for i, step in enumerate(plan):
        step_str = f"{i+1}. {step['device'].upper()}: {step['command']} {json.dumps(step['args'])}"
        fast_load(f"{C.INFO} {step_str}{C.END}", 0.04)
    print(f"\n{C.INFO}Actions: 'run', 'del <#>', 'edit <#> <key=val> <rationale>', 'add <dev> <cmd> <args> <rationale>'{C.END}")

# --- PRE-RECORDING BUFFER ---
time.sleep(0.5) 

# --- ANIMATION START ---
clear_terminal()
time.sleep(1.5) 

# --- THE REQUEST ---
sys.stdout.write(f"{C.OK}[RUN S:5 🔒]{C.END} {C.WARN}>{C.END} ")
sys.stdout.flush()
goal_text = "measure the spectrum of well h1. then turn on the stirring and add 70 ul of copper, 140 ul of bcs and 20 ul of hydroquinone. then park the sidekick. next, move the pybot to h1 which is located at -47, 122. important that any pybot move must be done at a z of 60 and a measurement is done at a height of 40. move the pybot to a height of 40, take a sensor reading with the pybot, and move it back to 60. next move the pybot arm to its park location of -100, 75, 60. Lastly, turn off the stirring, move sidekick to well h1 and measure the spectrum."
typewriter(goal_text, speed=0.015)

fast_load("[*] Goal received.", 0.3)
typewriter("[*] Thinking...", speed=0.03)
time.sleep(1.5)
print()

# Presenting the Plan Review
print_plan_review(ai_proposal)

# Action Approval
sys.stdout.write("Action > ")
sys.stdout.flush()
typewriter("run", speed=0.1)

# # Plan Execution Phase
# print(f"\n{C.INFO}Executing Plan (ID: 566)...{C.END}")
# total_steps = len(ai_proposal)
# for i, step in enumerate(ai_proposal):
#     dev = step['device']
#     cmd = step['command']
#     fast_load(f" -> Step {i+1}/{total_steps}: {dev}.{cmd}()... [{C.OK}OK{C.END}]", 0.06)
# print(f"{C.OK}Plan finished successfully.{C.END}\n")
# time.sleep(1.0)

# --- ANIMATION END ---

input("")